name: graphs # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: graphs
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
license: GPL-3.0
architectures:
  - build-on: amd64
  #- build-on: arm64


slots:
  graphs:
    interface: dbus
    bus: session
    name: se.sjoerd.Graphs

parts:
  matplotlib:
    source: https://github.com/matplotlib/matplotlib.git
    source-tag: 'v3.7.1'
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - cycler==0.11.0
      - fonttools==4.39.4
      - kiwisolver==1.4.4
      - contourpy==1.0.7
      - packaging==23.1
      - Pillow==9.5.0
      - pyparsing==3.0.9
      - scipy==1.10.1
      - numpy==1.24.3
      - python_dateutil==2.8.2
    prime:
      - -usr/bin/activate*
      - -usr/bin/Activate.ps1
      - -usr/bin/python*
      - -usr/bin/pip*
      - -pyvenv.cfg
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3.10/dist-packages
  blueprint-compiler:
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.8.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-prime: |
      echo 'Skip'
  graphs:
    after: [ blueprint-compiler ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/Sjoerd1993/Graphs.git
    #source-tag: 'v1.5.2'
    meson-parameters:
      - --prefix=/snap/graphs/current/usr
      - --buildtype=release
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/usr/lib/python3/dist-packages:$PYTHONPATH
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/snap/graphs.patch
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/graphs/current/usr/bin/graphs
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/graphs/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    organize:
      snap/graphs/current: .
      usr/lib/python3: usr/lib/python3.10
    parse-info: [usr/share/appdata/se.sjoerd.Graphs.appdata.xml]
    prime:
      - meta/*
      - usr/bin/graphs
      - usr/lib/python3.10/
      - usr/share/app*
      - usr/share/i*
      - usr/share/l*
      - usr/share/g*
    
apps:
  graphs:
    command: usr/bin/graphs
    desktop: usr/share/applications/se.sjoerd.Graphs.desktop
    common-id: se.sjoerd.Graphs
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
    extensions: [gnome]
